<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Author\StoreAuthorRequest;
use App\Http\Requests\Author\UpdateAuthorRequest;
use App\Http\Resources\AuthorResource;
use App\Models\Author;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Support\Facades\DB;

/**
 * @tag Author "Operations about authors"
 *
 * API AuthorController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class AuthorController extends Controller
{
    /**
     * Dapatkan 10 Penulis Teratas
     *
     * Mengambil daftar 10 penulis teratas berdasarkan jumlah rating di atas 5.
     */
    /**
     * Dapatkan 10 Penulis Teratas
     *
     * Mengambil daftar 10 penulis teratas berdasarkan jumlah rating di atas 5.
     *
     * @response 200 {"id": 1, "name": "Author Name", "voters": 10, "avg_author_rating": 8.5} "List of top authors"
     */
    public function top()
    {
        $authors = DB::table('authors')
            ->select(
                'authors.id',
                'authors.name',
                DB::raw('COUNT(ratings.id) AS voters'),
                DB::raw('AVG(ratings.rating) AS avg_author_rating') // Menambahkan perhitungan rata-rata rating
            )
            ->join('books', 'books.author_id', '=', 'authors.id')
            ->join('ratings', 'ratings.book_id', '=', 'books.id')
            ->where('ratings.rating', '>', 5)
            ->groupBy('authors.id', 'authors.name')
            ->orderBy('voters', 'desc')
            ->limit(10)
            ->get();

        // Cast the types to ensure correct JSON representation
        $authors = $authors->map(function ($author) {
            $author->id = (int) $author->id;
            $author->voters = (int) $author->voters;
            $author->avg_author_rating = round((float) $author->avg_author_rating, 1);

            return $author;
        });

        return response()->json($authors);
    }

    /**
     * Dapatkan Semua Penulis (Terpaginasi)
     *
     * Mengambil daftar penulis yang sudah dipaginasi, dengan 10 item per halaman.
     */
    /**
     * Dapatkan Semua Penulis (Terpaginasi)
     *
     * Mengambil daftar penulis yang sudah dipaginasi, dengan 10 item per halaman.
     *
     * @response 200 App\Http\Resources\AuthorResource[] "Paginated list of authors"
     */
    public function index(): AnonymousResourceCollection
    {
        $authors = Author::paginate(10);

        return AuthorResource::collection($authors);
    }

    /**
     * Buat Penulis Baru
     *
     * Menyimpan penulis yang baru dibuat ke dalam database.
     */
    /**
     * Buat Penulis Baru
     *
     * Menyimpan penulis yang baru dibuat ke dalam database.
     *
     * @body App\Http\Requests\Author\StoreAuthorRequest "New author data"
     *
     * @response 200 App\Http\Resources\AuthorResource "Created author"
     * @response 422 App\Http\Responses\ValidationException "Validation error"
     */
    public function store(StoreAuthorRequest $request): AuthorResource
    {
        $author = Author::create($request->validated());

        return new AuthorResource($author);
    }

    /**
     * Dapatkan Detail Penulis
     *
     * Mengambil detail penulis tertentu berdasarkan ID.
     */
    /**
     * Dapatkan Detail Penulis
     *
     * Mengambil detail penulis tertentu berdasarkan ID.
     *
     * @param int author "The author ID"
     *
     * @response 200 App\Http\Resources\AuthorResource "Author details"
     * @response 404 App\Http\Responses\ModelNotFoundException "Author not found"
     */
    public function show(Author $author): AuthorResource
    {
        return new AuthorResource($author);
    }

    /**
     * Perbarui Penulis
     *
     * Memperbarui detail penulis tertentu berdasarkan ID.
     */
    /**
     * Perbarui Penulis
     *
     * Memperbarui detail penulis tertentu berdasarkan ID.
     *
     * @param int author "The author ID"
     *
     * @body App\Http\Requests\Author\UpdateAuthorRequest "Updated author data"
     *
     * @response 200 App\Http\Resources\AuthorResource "Updated author"
     * @response 404 App\Http\Responses\ModelNotFoundException "Author not found"
     * @response 422 App\Http\Responses\ValidationException "Validation error"
     */
    public function update(UpdateAuthorRequest $request, Author $author): AuthorResource
    {
        $author->update($request->validated());

        return new AuthorResource($author);
    }

    /**
     * Hapus Penulis
     *
     * Menghapus penulis tertentu berdasarkan ID.
     */
    /**
     * Hapus Penulis
     *
     * Menghapus penulis tertentu berdasarkan ID.
     *
     * @param int author "The author ID"
     *
     * @response 204 "No content"
     * @response 404 App\Http\Responses\ModelNotFoundException "Author not found"
     */
    public function destroy(Author $author): \Illuminate\Http\Response
    {
        $author->delete();

        return response()->noContent();
    }
}
