<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\BookCategory\StoreBookCategoryRequest;
use App\Http\Requests\BookCategory\UpdateBookCategoryRequest;
use App\Http\Resources\BookCategoryResource;
use App\Models\BookCategory;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API BookCategoryController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookCategoryController extends Controller
{
    /**
     * Dapatkan Semua Kategori Buku
     *
     * Mengambil daftar kategori buku yang sudah dipaginasi.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = BookCategory::paginate();

        return BookCategoryResource::collection($models);
    }

    /**
     * Buat Kategori Buku Baru
     *
     * Menyimpan kategori buku yang baru dibuat ke dalam database.
     */
    public function store(StoreBookCategoryRequest $request): BookCategoryResource
    {
        $model = BookCategory::create($request->validated());

        return new BookCategoryResource($model);
    }

    /**
     * Dapatkan Detail Kategori Buku
     *
     * Mengambil detail kategori buku tertentu berdasarkan ID.
     */
    public function show(BookCategory $model): BookCategoryResource
    {
        return new BookCategoryResource($model);
    }

    /**
     * Perbarui Kategori Buku
     *
     * Memperbarui detail kategori buku tertentu berdasarkan ID.
     */
    public function update(UpdateBookCategoryRequest $request, BookCategory $model): BookCategoryResource
    {
        $model->update($request->validated());

        return new BookCategoryResource($model);
    }

    /**
     * Hapus Kategori Buku
     *
     * Menghapus kategori buku tertentu berdasarkan ID.
     */
    public function destroy(BookCategory $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
