<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Book\StoreBookRequest;
use App\Http\Requests\Book\UpdateBookRequest;
use App\Http\Resources\BookResource;
use App\Models\Book;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API BookController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookController extends Controller
{
    /**
     * Dapatkan Semua Buku
     *
     * Mengambil daftar buku yang sudah dipaginasi.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = Book::latest()->paginate(10);

        return BookResource::collection($models);
    }

    /**
     * Buat Buku Baru
     *
     * Menyimpan buku yang baru dibuat ke dalam database.
     */
    public function store(StoreBookRequest $request): BookResource
    {
        $model = Book::create($request->validated());

        return new BookResource($model);
    }

    /**
     * Dapatkan Detail Buku
     *
     * Mengambil detail buku tertentu berdasarkan ID.
     */
    public function show(Book $model): BookResource
    {
        return new BookResource($model);
    }

    /**
     * Perbarui Buku
     *
     * Memperbarui detail buku tertentu berdasarkan ID.
     */
    public function update(UpdateBookRequest $request, Book $model): BookResource
    {
        $model->update($request->validated());

        return new BookResource($model);
    }

    /**
     * Hapus Buku
     *
     * Menghapus buku tertentu berdasarkan ID.
     */
    public function destroy(Book $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
