<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\BookCategory\StoreBookCategoryRequest;
use App\Http\Requests\BookCategory\UpdateBookCategoryRequest;
use App\Http\Resources\BookCategoryResource;
use App\Models\BookCategory;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API BookCategoryController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = BookCategory::paginate();

        return BookCategoryResource::collection($models);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreBookCategoryRequest $request): BookCategoryResource
    {
        $model = BookCategory::create($request->validated());

        return new BookCategoryResource($model);
    }

    /**
     * Display the specified resource.
     */
    public function show(BookCategory $model): BookCategoryResource
    {
        return new BookCategoryResource($model);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateBookCategoryRequest $request, BookCategory $model): BookCategoryResource
    {
        $model->update($request->validated());

        return new BookCategoryResource($model);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(BookCategory $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
