<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\BookCategory\StoreBookCategoryRequest;
use App\Http\Requests\BookCategory\UpdateBookCategoryRequest;
use App\Http\Resources\BookCategoryResource;
use App\Models\BookCategory;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API BookCategoryController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookCategoryController extends Controller
{
    /**
     * Dapatkan Semua Kategori Buku (Terpaginasi)
     *
     * Mengambil daftar kategori buku yang sudah dipaginasi, dengan 10 item per halaman.
     */
    public function index(): AnonymousResourceCollection
    {
        $bookCategories = BookCategory::paginate(10);

        return BookCategoryResource::collection($bookCategories);
    }

    /**
     * Buat Kategori Buku Baru
     *
     * Menyimpan kategori buku yang baru dibuat ke dalam database.
     */
    public function store(StoreBookCategoryRequest $request): BookCategoryResource
    {
        $bookCategory = BookCategory::create($request->validated());

        return new BookCategoryResource($bookCategory);
    }

    /**
     * Dapatkan Detail Kategori Buku
     *
     * Mengambil detail kategori buku tertentu berdasarkan ID.
     */
    public function show(BookCategory $bookCategory): BookCategoryResource
    {
        return new BookCategoryResource($bookCategory);
    }

    /**
     * Perbarui Kategori Buku
     *
     * Memperbarui detail kategori buku tertentu berdasarkan ID.
     */
    public function update(UpdateBookCategoryRequest $request, BookCategory $bookCategory): BookCategoryResource
    {
        $bookCategory->update($request->validated());

        return new BookCategoryResource($bookCategory);
    }

    /**
     * Hapus Kategori Buku
     *
     * Menghapus kategori buku tertentu berdasarkan ID.
     */
    public function destroy(BookCategory $bookCategory): \Illuminate\Http\Response
    {
        $bookCategory->delete();

        return response()->noContent();
    }
}
