<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Http\Resources\CategoryResource;
use App\Models\Category;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API CategoryController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class CategoryController extends Controller
{
    /**
     * Dapatkan Semua Kategori
     *
     * Mengambil daftar kategori yang sudah dipaginasi.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = Category::paginate();

        return CategoryResource::collection($models);
    }

    /**
     * Buat Kategori Baru
     *
     * Menyimpan kategori yang baru dibuat ke dalam database.
     */
    public function store(StoreCategoryRequest $request): CategoryResource
    {
        $model = Category::create($request->validated());

        return new CategoryResource($model);
    }

    /**
     * Dapatkan Detail Kategori
     *
     * Mengambil detail kategori tertentu berdasarkan ID.
     */
    public function show(Category $model): CategoryResource
    {
        return new CategoryResource($model);
    }

    /**
     * Perbarui Kategori
     *
     * Memperbarui detail kategori tertentu berdasarkan ID.
     */
    public function update(UpdateCategoryRequest $request, Category $model): CategoryResource
    {
        $model->update($request->validated());

        return new CategoryResource($model);
    }

    /**
     * Hapus Kategori
     *
     * Menghapus kategori tertentu berdasarkan ID.
     */
    public function destroy(Category $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
