<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Http\Resources\CategoryResource;
use App\Models\Category;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API CategoryController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = Category::paginate();

        return CategoryResource::collection($models);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request): CategoryResource
    {
        $model = Category::create($request->validated());

        return new CategoryResource($model);
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $model): CategoryResource
    {
        return new CategoryResource($model);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Category $model): CategoryResource
    {
        $model->update($request->validated());

        return new CategoryResource($model);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
