<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Rating\StoreRatingRequest;
use App\Http\Requests\Rating\UpdateRatingRequest;
use App\Http\Resources\RatingResource;
use App\Models\Rating;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API RatingController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class RatingController extends Controller
{
    /**
     * Dapatkan Semua Rating (Terpaginasi)
     *
     * Mengambil daftar rating yang sudah dipaginasi, dengan 10 item per halaman.
     */
    public function index(): AnonymousResourceCollection
    {
        $ratings = Rating::paginate(10);

        return RatingResource::collection($ratings);
    }

    /**
     * Buat Rating Baru
     *
     * Menyimpan rating yang baru dibuat ke dalam database.
     */
    public function store(StoreRatingRequest $request): RatingResource
    {
        $rating = Rating::create($request->validated());

        return new RatingResource($rating);
    }

    /**
     * Dapatkan Detail Rating
     *
     * Mengambil detail rating tertentu berdasarkan ID.
     */
    public function show(Rating $rating): RatingResource
    {
        return new RatingResource($rating);
    }

    /**
     * Perbarui Rating
     *
     * Memperbarui detail rating tertentu berdasarkan ID.
     */
    public function update(UpdateRatingRequest $request, Rating $rating): RatingResource
    {
        $rating->update($request->validated());

        return new RatingResource($rating);
    }

    /**
     * Hapus Rating
     *
     * Menghapus rating tertentu berdasarkan ID.
     */
    public function destroy(Rating $rating): \Illuminate\Http\Response
    {
        $rating->delete();

        return response()->noContent();
    }
}
