<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Rating\StoreRatingRequest;
use App\Http\Requests\Rating\UpdateRatingRequest;
use App\Http\Resources\RatingResource;
use App\Models\Rating;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

/**
 * API RatingController
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class RatingController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): AnonymousResourceCollection
    {
        $models = Rating::paginate();

        return RatingResource::collection($models);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRatingRequest $request): RatingResource
    {
        $model = Rating::create($request->validated());

        return new RatingResource($model);
    }

    /**
     * Display the specified resource.
     */
    public function show(Rating $model): RatingResource
    {
        return new RatingResource($model);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRatingRequest $request, Rating $model): RatingResource
    {
        $model->update($request->validated());

        return new RatingResource($model);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Rating $model): \Illuminate\Http\Response
    {
        $model->delete();

        return response()->noContent();
    }
}
