<?php

declare(strict_types=1);

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * BookResource
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'author_id' => $this->author_id,
            'description' => $this->description,
            'published_year' => $this->published_year,
            'stock' => $this->stock,
            'price' => $this->price,
            'avg_rating' => $this->avg_rating,
            'voters_count' => $this->voters_count,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
