<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Author;
use App\Models\Book;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * BookFactory
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     */
    protected $model = Book::class;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'title' => $this->faker->sentence(3),
            'author_id' => Author::inRandomOrder()->first()->id ?? \App\Models\Author::factory(),
            'description' => $this->faker->paragraph(),
            'published_year' => $this->faker->year(),
            'stock' => $this->faker->numberBetween(0, 100),
            'price' => $this->faker->randomFloat(2, 10, 100),
            'avg_rating' => $this->faker->randomFloat(2, 1, 5),
            'voters_count' => $this->faker->numberBetween(0, 1000),
        ];
    }
}
