<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Book;
use App\Models\Category;
use App\Models\BookCategory;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * BookCategoryFactory
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class BookCategoryFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     */
    protected $model = BookCategory::class;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'book_id' => Book::inRandomOrder()->first()->id ?? \App\Models\Book::factory(),
            'category_id' => Category::inRandomOrder()->first()->id ?? \App\Models\Category::factory(),
        ];
    }
}
