<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * CategoryFactory
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class CategoryFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     */
    protected $model = Category::class;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'name' => $this->faker->unique(false, 500000)->sentence(3),
            'description' => $this->faker->sentence(),
        ];
    }
}
