<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Book;
use App\Models\User;
use App\Models\Rating;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * RatingFactory
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class RatingFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     */
    protected $model = Rating::class;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        return [
            'book_id' => Book::inRandomOrder()->first()->id ?? \App\Models\Book::factory(),
            'user_id' => User::inRandomOrder()->first()->id ?? \App\Models\User::factory(),
            'rating' => $this->faker->numberBetween(1, 10),
            'comment' => $this->faker->paragraph(),
        ];
    }
}
