<?php

declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * StoreBookRequest
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class StoreBookRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'title' => ['required', 'string', 'max:255'],
            'author_id' => ['required', 'integer', 'exists:authors,id'],
            'description' => ['required', 'string', 'max:65535'],
            'published_year' => ['required', 'integer', 'digits:4'],
            'stock' => ['required', 'integer'],
            'price' => ['required', 'numeric'],
            'avg_rating' => ['numeric'],
            'voters_count' => ['integer'],
        ];
    }
}
