<?php

declare(strict_types=1);

namespace App\Http\Requests\Book;

use Illuminate\Foundation\Http\FormRequest;

/**
 * UpdateBookRequest
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class UpdateBookRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'title' => ['sometimes', 'string', 'max:255'],
            'author_id' => ['sometimes', 'integer', 'exists:authors,id'],
            'description' => ['sometimes', 'string', 'max:65535'],
            'published_year' => ['sometimes', 'integer', 'digits:4'],
            'stock' => ['sometimes', 'integer'],
            'price' => ['sometimes', 'numeric'],
            // 'avg_rating' => ['sometimes', 'numeric'],
            // 'voters_count' => ['sometimes', 'integer'],
        ];
    }
}
