<?php

declare(strict_types=1);

namespace App\Http\Requests\BookCategory;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * StoreBookCategoryRequest
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class StoreBookCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'book_id' => ['required', 'integer', 'exists:books,id'],
            'category_id' => [
                'required',
                'integer',
                'exists:categories,id',
                Rule::unique('book_categories')->where(function ($query) {
                    return $query->where('book_id', $this->input('book_id'));
                }),
            ],
        ];
    }
}
