<?php

declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * UpdateBookCategoryRequest
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class UpdateBookCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'book_id' => ['sometimes', 'integer', 'exists:books,id'],
            'category_id' => [
                'sometimes',
                'integer',
                'exists:categories,id',
                Rule::unique('book_categories')->where(function ($query) {
                    return $query->where('book_id', $this->input('book_id'));
                })->ignore($this->book_category->id),
            ],
        ];
    }
}
