<?php

declare(strict_types=1);

namespace App\Http\Requests\Rating;

use Illuminate\Foundation\Http\FormRequest;

/**
 * StoreRatingRequest
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
class StoreRatingRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'book_id' => ['required', 'integer', 'exists:books,id'],
            'user_id' => ['required', 'integer', 'exists:users,id'],
            'rating' => ['required', 'integer', 'min:1', 'max:10'],
            'comment' => ['nullable', 'string'],
        ];
    }
}
