<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Author Model
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
final class Author extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     */
    protected $table = 'authors';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'bio',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'name' => 'string',
        'bio' => 'string',
    ];

    public function books(): HasMany
    {
        return $this->hasMany(Book::class);
    }
}
