<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Book Model
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
final class Book extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     */
    protected $table = 'books';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'title',
        'author_id',
        'description',
        'published_year',
        'stock',
        'price',
        'avg_rating',
        'voters_count',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'title' => 'string',
        'author_id' => 'integer',
        'description' => 'string',
        'published_year' => 'integer',
        'stock' => 'integer',
        'price' => 'decimal:2',
        'avg_rating' => 'float',
        'voters_count' => 'integer',
    ];

    /**
     * Get the book_categories for this model.
     */
    public function book_categories(): HasMany
    {
        return $this->hasMany(BookCategory::class);
    }

    public function ratings(): HasMany
    {
        return $this->hasMany(Rating::class);
    }
}
