<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * BookCategory Model
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
final class BookCategory extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     */
    protected $table = 'book_categories';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'book_id',
        'category_id',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'book_id' => 'integer',
        'category_id' => 'integer',
    ];

    /**
     * Get the book that owns this model.
     */
    public function book(): BelongsTo
    {
        return $this->belongsTo(Book::class);
    }

    /**
     * Get the category that owns this model.
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}
