<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Rating Model
 * Generated by ModelSchema Enterprise Fragment Architecture
 */
final class Rating extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     */
    protected $table = 'ratings';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'book_id',
        'user_id',
        'rating',
        'comment',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'book_id' => 'integer',
        'user_id' => 'integer',
        'rating' => 'integer',
        'comment' => 'string',
    ];

    /**
     * Get the user that owns this model.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the book that owns this model.
     */
    public function book(): BelongsTo
    {
        return $this->belongsTo(Book::class);
    }
}
